# Nombre del paquete
package_name: modelo-abandono

# Archivos de datos
train_data_file: cultivos_train.csv
test_data_file: cultivos_test.csv

# Variables
# Objetivo
target: RENDIMIENTO_TONELADAS_HA

features:
  - ANIO
  - NUM_CLUSTERS
  - NOMBRE_CULTIVO

temp_features:
 - CODIGO_DEPARTAMENTO
 - NOMBRE_DEPARTAMENTO
 - CODIGO_MUNICIPIO
 - NOMBRE_MUNICIPIO
 - GRUPO_CULTIVO
 - SUBGRUPO_CULTIVO
 - REGION_SISTEMA
 - PERIODO
 - AREA_SIEMBRA_HA
 - AREA_COSECHA_HA
 - PRODUCCION_TONELADAS
 - AREA_SIEMBRA_HA
 - AREA_COSECHA_HA
 - PRODUCCION_TONELADAS


# pipelines
pipeline_name: modelo-abandono
pipeline_save_file: modelo-abandono-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
n_estimators: 500

max_depth: 10

# variables a mapear
qual_vars:
  - NOMBRE_CULTIVO

 
categorical_vars:
  - NOMBRE_CULTIVO

# mapeo de variables
qual_mappings:
 CAUCHO: 1
 MAIZ: 2
 MARACUYA: 3
 UVA: 4
 FRIJOL: 5
 PLATANO: 6
 CACAO: 7
 PIÑA: 8
 ARVEJA: 9
 LECHUGA: 10
 YUCA: 11
 NARANJA: 12
 MANDARINA: 13
 HELICONIA: 14
 MANI: 15
 CILANTRO: 16
 BANANO: 17
 FLORES Y FOLLAJES: 18
 AGUACATE: 19
 FRESA: 20
 GRANADILLA: 21
 CAFE: 22
 CITRICOS: 23
 ARROZ: 24
 CAÑA PANELERA: 25
 PAPA: 26
 TRIGO: 27
 ARRACACHA: 28
 LIMON: 29
 TOMATE: 30
 GUANDUL: 31
 PAPAYA: 32
 PALMA DE ACEITE: 33
 TOMATE DE ARBOL: 34
 HABICHUELA: 35
 SABILA: 36
 COCO: 37
 GUANABANA: 38
 ZAPOTE: 39
 LULO: 40
 CEBADA: 41
 AJI: 42
 QUINUA: 43
 ESPINACA: 44
 HORTALIZAS VARIAS: 45
 SOYA: 46
 HABA: 47
 CHIRIMOYA: 48
 CIMARRON: 49
 ZANAHORIA: 50
 MORA: 51
 ALFALFA: 52
 PEPINO GUISO: 53
 PATILLA: 54
 DURAZNO: 55
 GUAYABA: 56
 PEPINO COHOMBRO: 57
 FIQUE: 58
 AHUYAMA: 59
 IRACA: 60
 CEBOLLA DE BULBO: 61
 ÑAME: 62
 CHONTADURO: 63
 PITAHAYA: 64
 PIMENTON: 65
 ALBAHACA: 66
 PLANTAS AROMATICAS: 67
 FEIJOA: 68
 MANGO: 69
 CEBOLLA DE RAMA: 70
 MELON: 71
 ACHIRA: 72
 APIO: 73
 BROCOLI: 74
 GUAMA: 75
 ASAI: 76
 MALANGA: 77
 CHOLUPA: 78
 BADEA: 79
 COL: 80
 ALGODON: 81
 ACELGA: 82
 TABACO RUBIO: 83
 UCHUVA: 84
 REPOLLO: 85
 GULUPA: 86
 CAÑA MIEL: 87
 SORGO: 88
 COLIFLOR: 89
 CURUBA: 90
 MANZANA: 91
 TOMILLO: 92
 AJO: 93
 ANIS: 94
 BERENJENA: 95
 BREVO: 96
 ANTURIO: 97
 ULLUCO: 98
 BATATA: 99
 ARANDANO: 100
 ACHIOTE: 101
 CADUCIFOLIOS: 102
 BOROJO: 103
 TABACO NEGRO: 104
 HELECHO: 105
 BANANITO: 106
 CIRUELA: 107
 PEREJIL: 108
 CALABAZA: 109
 AJONJOLI: 110
 LIMA: 111
 ESPARRAGO: 112
 RUSCUS: 113
 TAMARINDO: 114
 REMOLACHA: 115
 PALMITO: 116
 CRISANTEMO: 117
 CURCUMA: 118
 AVENA: 119
 PLANTAS AROMATICAS Y MEDICINALES: 120
 ARAZA: 121
 NISPERO: 122
 EUCALIPTO BABY BLUE: 123
 PAPAYUELA: 124
 YACON: 125
 DATIL: 126
 PLANTAS MEDICINALES: 127
 TANGELO: 128
 MAIZ FORRAJERO: 129
 JENJIBRE: 130
 PEPA DE PAN: 131
 STEVIA: 132
 SACHA INCHI: 133
 PERA: 134
 COPOAZU: 135
 ESTROPAJO: 136
 MACADAMIA: 137
 CLAVEL: 138
 HORTENSIA: 139
 NONI: 140
 PALMA AMARGA: 141
 ROSA: 142
 CAÑA FLECHA: 143
 FRAMBUESA: 144
 MIMBRE: 145
 MANGOSTINO: 146
 PUERRO: 147
 CALABACIN: 148
 PALMA ROBELINA: 149
 POMELO: 150
 PIMIENTA: 151
 GIRASOL: 152
 LIMONARIA: 153
 CEBOLLIN: 154
 FRUTALES VARIOS: 155
 FLOR DE JAMAICA: 156
 UMARI: 157
 AGRAZ: 158
 AGUAJE: 159
 ASTROMELIA: 160
 CENTENO: 161
 CHONQUE: 162
 MARAÑON: 163
 RABANO: 164
 GUATILA: 165
 OREGANO: 166
 CARDAMOMO: 167
 RUDA: 168
 GLADIOLO: 169
 MENTA: 170
 HIGO: 171
 ACHICORIA: 172
 MAMONCILLO: 173
 POLEO: 174
 HIGUERILLA: 175
 ASPARRAGUS: 176
 GARBANZO: 177
 CHIA: 178
 UVA CAIMARONA: 179
 ANON: 180
 AMARANTO: 181
 COCCULUS: 182
 TORONJOA: 183
 ROMERO: 184
 CHAMBA: 185
 COCONA: 186
 MORERA: 187
 NABO: 188
 FLOR DE SAFARI: 189
 TE: 190
 ALGARROBO: 191
 CAIMO: 192
 CHACHAFRUTO: 193
 RAMBUTAN: 194
 JATROPHA: 195
 ORQUIDEA: 196
 CALENDULA: 197
 FITOSPORUM: 198
 TREE FERN: 199
 TANGARANA: 200
 CHAMPIÑON: 201
 LENTEJA: 202
 ESPARTO: 203
 ORELLANA: 204
 PROTEA: 205
 RUBA: 206
 MANZANILLA: 207
 LIMONIUM: 208
 MAMEY: 209
 COROZO: 210
 POMARROSA: 211
 BORE: 212
 STATICE: 213
 ENELDO: 214
 BACURI: 215




