# Nombre del paquete
package_name: model-recomendar-cultivo

# Archivos de datos
train_data_file: cultivos_train.csv
test_data_file: cultivos_test.csv

# Variables
# Objetivo
target: RENDIMIENTO_TONELADAS_HA


features:
  - ANIO
  - NOMBRE_CULTIVO
  - NUM_CLUSTERS

temp_features:
- CODIGO_DEPARTAMENTO
- NOMBRE_DEPARTAMENTO
- CODIGO_MUNICIPIO
- NOMBRE_MUNICIPIO
- GRUPO_CULTIVO
- SUBGRUPO_CULTIVO
- NOMBRE_CULTIVO
- REGION_SISTEMA
- ANIO
- PERIODO
- AREA_SIEMBRA_HA
- AREA_COSECHA_HA
- PRODUCCION_TONELADAS
- RENDIMIENTO_TONELADAS_HA
- ESTADO_PRODUCCION
- NOMBRE_CIENTIFICO,
- CICLO_CULTIVO
- NUM_CLUSTERS

# pipelines
pipeline_name: modelo-model-recomendar-cultivo
pipeline_save_file: model-recomendar-cultivo-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
n_estimators: 500
max_depth: 4
min_samples_split: 5
learning_rate: 0.01

# variables a mapear
qual_vars:
  - RENDIMIENTO_TONELADAS_HA

# 
#categorical_vars:
#  - Attrition_Flag

# mapeo de variables
#qual_mappings:
#  Attrited Customer: 1
#  Existing Customer: 0

