# Nombre del paquete
package_name: model-recomendar-cultivo

# Archivos de datos
train_data_file: cultivos_train.csv
test_data_file: cultivos_test.csv

# Objetivo
target: RENDIMIENTO_TONELADAS_HA

#Variables 
features:
  - ANIO
  - NOMBRE_CULTIVO
  - NUM_CLUSTERS

temp_features:
- CODIGO_DEPARTAMENTO
- NOMBRE_DEPARTAMENTO
- CODIGO_MUNICIPIO
- NOMBRE_MUNICIPIO
- GRUPO_CULTIVO
- SUBGRUPO_CULTIVO
- NOMBRE_CULTIVO
- REGION_SISTEMA
- ANIO
- PERIODO
- AREA_SIEMBRA_HA
- AREA_COSECHA_HA
- PRODUCCION_TONELADAS
- RENDIMIENTO_TONELADAS_HA
- ESTADO_PRODUCCION
- NOMBRE_CIENTIFICO
- CICLO_CULTIVO
- NUM_CLUSTERS

# pipelines
pipeline_name: model-recomendar-cultivo
pipeline_save_file: model-recomendar-cultivo-output

# fracci칩n del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperpar치metros del modelo 
# Configuraci칩n para el modelo de regresi칩n de aumento de gradiente

n_estimators: 500
max_depth: 4
min_samples_split: 5
learning_rate: 0.01
loss: squared_error


# variables a mapear
qual_vars:
  - NOMBRE_DEPARTAMENTO
  - NOMBRE_CULTIVO
 
# 
categorical_vars:
  - NOMBRE_DEPARTAMENTO
  - NOMBRE_CULTIVO


# mapeo de variables
#qual_mappings:



